### ISSUE TITLE
README.md image bug

### ISSUE THREAD

**Issue by oleksandr-bilyk** [Microsoft/Windows-iotcore-samples#118]
Windows-iotcore-samples/Samples/OpenCVExample/CPP/README.md contains bad link to image in "Modify you General Properties" paragraph. You may fix it quickly because file is there "https://github.com/Microsoft/Windows-iotcore-samples/tree/develop/Resources/images/OpenCV/add_libs.PNG"

![image](https://user-images.githubusercontent.com/17872879/37397302-f006ba14-2783-11e8-803e-4a20b5dd4826.png)

**Comment by saraclay** [comment]
Thank you @oleksandr-bilyk! I have fixed this on the develop branch.
