### ISSUE TITLE
FORCE_OOBE_WELCOME_SCREEN macro is defined for Debug|ARM, Debug|x86, but not for Debug|x64

### ISSUE THREAD

**Issue by sergeyDoroshenko** [Microsoft/Windows-iotcore-samples#120]
Minor issue:
FORCE_OOBE_WELCOME_SCREEN macro is defined for Debug|ARM, Debug|x86, but not for Debug|x64.
It probably should be defined for all debug configs  (ARM, x86, x64) or for none of them.

**Comment by saraclay** [comment]
Hi @sergeyDoroshenko - what sample are you referring to?
