### ISSUE TITLE
Link to Download Zip of samples broken link.

### ISSUE THREAD

**Issue by JohnDrinkall** [Microsoft/Windows-iotcore-samples#124]
There seems to have been a lot of moving destinations around recently.
The Windows IoT Core (https://developer.microsoft.com/en-us/windows/iot/samples)
no longer links to samples.
The path seems to have been changed from master to develop. Is this intentional?
e.g. Original link
https://github.com/Microsoft/Windows-iotcore-samples/tree/master/Samples/HelloBlinky
Actual link.
https://github.com/Microsoft/Windows-iotcore-samples/tree/develop/Samples/HelloBlinky

**Comment by saraclay** [comment]
Hi John, due to a bit of a fire we had to put out, those links were temporarily changed to develop. They are back to master now.
