### ISSUE TITLE
Event hub non operational on IOT core 

### ISSUE THREAD

**Issue by Bhairav-Pardiwala** [Microsoft/Windows-iotcore-samples#127]
Hello 

I have tried to make event hubs of azure sample to windows iot core and it does not work .(The iot hub sample works fine )

Should event hubs be used  in IOT core ?
Pls refer https://github.com/MicrosoftDocs/azure-docs/issues/6249

**Comment by gmileka** [comment]
Hi Bhairav, could you please point us to the sample you have tried?

**Comment by Bhairav-Pardiwala** [comment]
I believe its this one which did not work 

https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dotnet-standard-getstarted-send

But does not matter i found out that IOT hub sample worked properly for me
