### ISSUE TITLE
Serial UART Sample works fine with Raspberri Pi3 but fails on Dragonboard

### ISSUE THREAD

**Issue by omarbarlas** [Microsoft/Windows-iotcore-samples#142]
This sample code works fine on Raspberri Pi 3 with Windows 10 IOT but failing when ran on DragonBoard 410C 

serialPort = await SerialDevice.FromIdAsync(dis[0].Id)

returns null although dis[0].Id has some data in it.

**Comment by saraclay** [comment]
Hi @omarbarlas - This is a known issue. Qualcomm made a change to the BSP that removed the UARTS. We are working to fix this.
