### ISSUE TITLE
SerialUART sample (CS) hides bug at SerialDevice

### ISSUE THREAD

**Issue by Hevgen** [Microsoft/Windows-iotcore-samples#149]
SerialUART sample's C# codes hide artful bug that exists at SerialDevice class. More details below.

The bug: not all SerialDevice settings are applied after corresponding properties set. The same properties should be read before reading something from the device.

MainPage.xaml.cs has lines 94..101:
`                // Configure serial settings
                serialPort.WriteTimeout = TimeSpan.FromMilliseconds(1000);
                serialPort.ReadTimeout = TimeSpan.FromMilliseconds(1000);                
                serialPort.BaudRate = 9600;
                serialPort.Parity = SerialParity.None;
                serialPort.StopBits = SerialStopBitCount.One;
                serialPort.DataBits = 8;
                serialPort.Handshake = SerialHandshake.None;`

Actually, this lines has no sense without next lines 103..108:
`                // Display configured settings
                status.Text = "Serial port configured successfully: ";
                status.Text += serialPort.BaudRate + "-";
                status.Text += serialPort.DataBits + "-";
                status.Text += serialPort.Parity.ToString() + "-";
                status.Text += serialPort.StopBits;`

So bug may be reproduced easily by commenting lines 104..108 and using non-default settings at lines 95..101. This cause that you will never get into line 264 (`if (bytesRead > 0)`).

We found this bug then we tried to create own project using this sample codes with BaudRate=115200.

I think that corresponding attention note should be included in the sample before till the bug fix. 

P.S.
We don't see a proper way to make bug-report except this issue and Windows Platform Developer (WPDev) Feedback voice.

**Comment by saraclay** [comment]
Hi @Hevgen, thank you for reporting this bug. Could you please file this using the instructions for Feedback Hub at the following link? Thank you! https://social.msdn.microsoft.com/Forums/en-US/fad1c6a0-e578-44a7-8e8d-95cc28c06ccd/need-logs-if-your-device-hasnt-updated-to-the-latest-iotcore-version?forum=WindowsIoT
