### ISSUE TITLE
Serial UART deleted as dupplicate?

### ISSUE THREAD

**Issue by PRIMETSS** [Microsoft/Windows-iotcore-samples#165]
Seems Serial UART got deleted as may have been duplicate, but seems Both SerialUART and CustomSerialDeviceAccess have both been removed? Is this intenttional?

https://github.com/Microsoft/Windows-iotcore-samples/issues/153

Also 'SerialUART' seems worthy of a separate project amongst the notable others, as its a very common device for most IoT projects.

**Comment by saraclay** [comment]
This has been reverted. Thank you for the heads-up.
