### ISSUE TITLE
IoT Startup App Sample's images are broken

### ISSUE THREAD

**Issue by JonathanPalmerGD** [Microsoft/Windows-iotcore-samples#223]
The pictures on the README.md of https://github.com/Microsoft/Windows-iotcore-samples/blob/develop/Samples/IoTStartApp/Cpp/README.md show up as broken icons.

![brokenimages](https://user-images.githubusercontent.com/2644214/46235035-5ca40d80-c32d-11e8-9d6b-4aaa5dd2a72a.PNG)

**Comment by saraclay** [comment]
This has been fixed.
