### ISSUE TITLE
Link to docs are broken

### ISSUE THREAD

**Issue by xantiva** [Microsoft/Windows-iotcore-samples#232]
Hi,

for example in theSerial UART sample:
https://github.com/Microsoft/Windows-iotcore-samples/tree/develop/Samples/SerialUART/CS

Link to the headless mode: https://github.com/Microsoft/Windows-iotcore-samples/blob/develop/Docs/HeadlessMode
or MPM pin mapping page: https://github.com/Microsoft/Windows-iotcore-samples/blob/develop/Samples/PinMappingsMBM

result in #404 not found error pages. Please fix the links to the docs.

Thank you.

**Comment by saraclay** [comment]
Thank you for the heads-up. @insomnux created a PR to fix this.
