### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by kn-neelalohitha** [Microsoft/Windows-iotcore-samples#233]
# What happened?
I was going through [README.md](https://github.com/Microsoft/Windows-iotcore-samples/blob/develop/README.md) as I was interested to learn about Windows 10 IoT Core and use it for my project.When I clicked on "Get Started" it redirected to [Error 404 - "Sorry, we couldn't find that page."](https://developer.microsoft.com/en-us/windows/iot/getstarted)

# What you expect to happen?
I expected to be taken to "Get Started" guide of Windows 10 IoT Core.

# Reference:
In [README.md](https://github.com/Microsoft/Windows-iotcore-samples/blob/develop/README.md) under the first paragraph of **Windows 10 IoT Core samples** in the **Note** section go to line 5 : **Get Started**.

**Comment by kn-neelalohitha** [comment]
Raised PR : [#234](https://github.com/Microsoft/Windows-iotcore-samples/pull/234).
Replaced the broken link in README.md with the "**Get Started**" link in [Windows 10 IoT documentation](https://docs.microsoft.com/en-us/windows/iot-core/).
Please review.

**Comment by saraclay** [comment]
Done! Thanks so much, @kn-neelalohitha!

**Comment by kn-neelalohitha** [comment]
@saraclay You are welcome and I am always glad to contribute!
