### ISSUE TITLE
Connecting to EAP-TLS network with certificates fails using WifiConnector

### ISSUE THREAD

**Issue by glwright** [Microsoft/Windows-iotcore-samples#238]
Hello, I am trying to use the WifiConnector sample to connect to a network that uses EAP-TLS with client and root certificates. In your readme you say that if the certificates are installed on the machine already that just clicking "Connect" will work.

"For networks that support Extensible Authentication Protocol (EAP), also known as Enterprise WiFi authentication, a password checkbox will be shown. **If your enterprise network device is configured with the required certificates, you can simply click Connect.**"

This is not working for me through the sample app unfortunately. It currently works when i use the Windows 10 built in wireless manager, but not the sample application. Do you know what else is required in the WifiConnector app to be able to connect to these networks? How does the built in manager do it? With the native wifi APIs you could specify in the profile which certificate to use, but I see no way with the WinRT APIs to do this.

Thank you for your help.

**Comment by saraclay** [comment]
Hi @glwright, do you mind reposting this on our MSDN forums? Asking because this may go beyond the sample, and we have staff dedicated to answering your questions on the forums. 

The link is here: https://social.msdn.microsoft.com/forums/en-US/home?forum=WindowsIoT
