### ISSUE TITLE
Invalid link to IoT Browser

### ISSUE THREAD

**Issue by Ruffio** [Microsoft/Windows-iotcore-samples#245]
On the frontpage (https://github.com/Microsoft/Windows-iotcore-samples) the link to IoT Browser is invalid. It points to: https://github.com/Microsoft/Windows-iotcore-samples/blob/develop/Samples/IotBrowser

When clicking the link you end up at:
![image](https://user-images.githubusercontent.com/1877612/49145921-38e74e80-f301-11e8-9d9a-3733f17c0f6a.png)

**Comment by saraclay** [comment]
Thanks! We're making this change right now.
