### ISSUE TITLE
Invalid link to IoT Onboarding

### ISSUE THREAD

**Issue by Ruffio** [Microsoft/Windows-iotcore-samples#246]
On the frontpage (https://github.com/Microsoft/Windows-iotcore-samples) the link to IoT Onboarding is invalid. It points to:https://github.com/Microsoft/Windows-iotcore-samples/blob/develop/Samples/IotOnboarding

When clicking the link you end up at:
![image](https://user-images.githubusercontent.com/1877612/49157934-4b718000-f321-11e8-8fc5-389ecdd0eaea.png)

**Comment by saraclay** [comment]
Thank you!
