### ISSUE TITLE
system.private.networking

### ISSUE THREAD

**Issue by greglaserstar** [Microsoft/Windows-iotcore-samples#248]
When I try to build the serialuart project I get the error Cannot resolve Assembly: System.Private.Networking version 4.0

What is this and how do I add it or get it in the right place, I am on Win 10 64, do I even need it can I comment out something if it doesn't have anything to do with the serial communications.
Thanks
Greg Anderson

**Comment by saraclay** [comment]
Hi @greglaserstar - could you please post this on our forums? 
https://social.msdn.microsoft.com/forums/en-US/home?forum=WindowsIoT
