### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by ScapinFranco** [Microsoft/Windows-iotcore-samples#310]
There are some assets missing in IoTCoreDefaultApp

Error		Payload file 'C:\Projects\IoTCoreDefaultApp\CS\SmartDisplay\Assets\Images\MSC17_avatars_people_023a.png' does not exist.	SmartDisplay			
Error		Payload file 'C:\Projects\IoTCoreDefaultApp\CS\SmartDisplay\Assets\Images\music-icon.png' does not exist.	SmartDisplay			
Error		Payload file 'C:\Projects\IoTCoreDefaultApp\CS\SmartDisplay\Assets\Images\robot-transparent.png' does not exist.	SmartDisplay			
Error		Payload file 'C:\Projects\IoTCoreDefaultApp\CS\SmartDisplay\Assets\Fonts\MSNMDL2.ttf' does not exist.	SmartDisplay			
Error		Payload file 'C:\Projects\IoTCoreDefaultApp\CS\SmartDisplay\Assets\Images\weather-icon.png' does not exist.	SmartDisplay

**Comment by saraclay** [comment]
This has been fixed. Thanks for filing this issue!
