### ISSUE TITLE
IoT Core project templates for VS2019

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/Windows-iotcore-samples#334]
Will you make the [IoT Core project templates](https://github.com/ms-iot/samples/tree/develop/IotTemplates/WindowsIotCoreTemplates) available for VS2019?

I'm asking the question here since the original repo is archived.

**Comment by saraclay** [comment]
@hansmbakker I'm checking with the team. Stay tuned.

**Comment by saraclay** [comment]
Yes, they are available for VS2019!

**Comment by paulmon** [comment]
There is a new repo also, that is not archived: https://github.com/ms-iot/vs-project-templates/tree/master/WindowsIotCoreTemplates

and the Visual Studio marketplace page is here: https://marketplace.visualstudio.com/items?itemName=MicrosoftIoT.WindowsIoTCoreProjectTemplatesforVS15

**Comment by hansmbakker** [comment]
Thank you! Then this can be closed
