### ISSUE TITLE
Pointed the wrong project template in get started tutorial.

### ISSUE THREAD

**Issue by luyaok** [Microsoft/Windows-iotcore-samples#341]
I followed this sample tutorial: https://github.com/Microsoft/Windows-iotcore-samples/tree/develop/Samples/MemoryStatus/CPP .
And found that in "To create you own project" step, it is said to "select the template 'Blank Windows IoT Core Console Application'" but in the picture below show another template: "Background Application (IoT)" in the red rectangle box.

**Comment by saraclay** [comment]
Thank you! This has been fixed.
