### ISSUE TITLE
Why can't use the diagnostic tools after combine two projects?

### ISSUE THREAD

**Issue by moyanming** [Microsoft/Windows-iotcore-samples#350]
Hi, 
According to the steps [here](https://github.com/Microsoft/Windows-iotcore-samples/tree/develop/Samples/ForegroundAppWithBackgroundApp/CS), all works fine. But why the diagnostic tools can't be used when debugging?

**Comment by saraclay** [comment]
@moyanming where does it say that the tools can't be used when debugging? Have you tried it?

**Comment by moyanming** [comment]
Hi @saraclay ,
Yes, I have test this combine solution but there is no diagnostic when debugging.
![QQ截图20190409201848](https://user-images.githubusercontent.com/13234209/55802674-49a79c80-5b0b-11e9-85b1-8e60ad70eb5c.jpg)

**Comment by paulmon** [comment]
The diagnostic tools do not work with background applications.  Could that be your problem?

**Comment by moyanming** [comment]
Hi @paulmon ,
17763.253, DB410C
The "MyForegroundApp" is the startup project. Why there is no foreground app but only have the background app after deploy this solution?
![QQ截图20190412115317](https://user-images.githubusercontent.com/13234209/56011313-ab3d5600-5d19-11e9-90d6-eaf010cff4eb.jpg)

Which type of this solution is, foreground or background?
How to debug the foreground one (MyForegroundApp) as there is no foreground app was deployed?

**Comment by moyanming** [comment]
BTW, please note that there is another two same name app, headed and headless are all have the same name "MyTestWDPHeadless-uwp_...". This project is a background app but I added a BlankApp (foreground) into this solustion refers [here](https://docs.microsoft.com/en-us/windows-hardware/service/iot/servicing-msstore#special-instructions-for-headless-apps).
What is the different between solutions of combine one and this project (MyTestWDPHeadless)?
![QQ截图20190412121219](https://user-images.githubusercontent.com/13234209/56011883-59e29600-5d1c-11e9-9126-f4d97ee08339.jpg)

**Comment by paulmon** [comment]
> 1. Why there is no foreground app but only have the background app in the WDP after deployed this solution?
This is a known issue.  The foreground app should be displayed but it isn't

> 2. Why the name of the backgournd app is "MyForegroundApp" but not "MyBackgroundApplication"?
>    ![QQ截图20190412115317](https://user-images.githubusercontent.com/13234209/56011313-ab3d5600-5d19-11e9-90d6-eaf010cff4eb.jpg)
The name comes from the appxmanifest and is the package name not the Visual Studio project name.

> 3. Which type of this solution is, foreground or background?
It is both.

> 4. How to debug the foreground one (MyForegroundApp) as there is no foreground app in the WDP?
Select the foreground app as the startup app in Visual Studio and press F5

> 5. There are two same name apps of this solution (usb "iotstartup list") after deployed: one is headed and another one is headless. This is confused.
This is by design.  The format is the <package name>!<Application>.  !App identifies which <Application> in the appxmanifest is being identified.  Headless means that the thing identified is a BackgroundTask of type "startup"

**Comment by paulmon** [comment]
> 6. What is the different between solutions of combine one and this project (MyTestWDPHeadless)?

The solution [here](https://docs.microsoft.com/en-us/windows-hardware/service/iot/servicing-msstore#special-instructions-for-headless-apps) creates a backgroundApp with stubbed foreground app that does nothing.  A foreground app is required to publish a background app to the store, even if the foreground does nothing.  As far as I know the scenario where the foreground app does nothing is only allowed on Windows IoT Core.
