### ISSUE TITLE
Controller Area Network Example for Window IOT

### ISSUE THREAD

**Issue by prbandaru** [microsoft/Windows-iotcore-samples#367]
Hello,

We are trying to use Windows IOT in Time Critical Application using Controller Area Network(CAN/J1939). I couldn't find any example which can receive data at a minimal periodicity of 10msec and interrupts being enabled. Can any one help us out on this, We are using Interl Atom processor.

**Comment by saraclay** [comment]
Please post this on [our forums](https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=WindowsIoT). Our GitHub issues are for documentation related inquiries only. Thank you.
