### ISSUE TITLE
Where's the ShellLauncher XML schemas?

### ISSUE THREAD

**Issue by forderud** [Microsoft/Windows-iotcore-samples#491]
The `ShellLauncher` XML schema URLs used by e.g. [ShellLauncherAzureADMultiUser.xml](https://github.com/microsoft/Windows-iotcore-samples/blob/develop/Samples/ShellLauncherV2/SampleConfigXmls/ShellLauncherAzureADMultiUser.xml) appear broken. This makes it difficult to learn how to configure custom shells, since schema documentation appear unavailable.

I'm experiencing the following error when attempting to access either `http://schemas.microsoft.com/ShellLauncher/2018/Configuration` or `http://schemas.microsoft.com/ShellLauncher/2019/Configuration`:
 **The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.**

Can someone please either restore the broken links or update the samples with working XML schema links?

**Comment by VoxCodice** [comment]
https://learn.microsoft.com/en-us/windows/client-management/mdm/assignedaccess-csp#shelllauncherconfiguration-xsd

**Comment by forderud** [comment]
Thanks

**Comment by VoxCodice** [comment]
My pleasure. It's a shame the repo owners don't seem to really check these issues anymore. Who knows, maybe they expect us to take up MSDN courses or something.
