### ISSUE TITLE
It's hard to accept incoming bluetooth pairing requests

### ISSUE THREAD

**Issue by sergeyDoroshenko** [Microsoft/Windows-iotcore-samples#76]
"IoT Core Default App" uses the same ObservableCollection instance for keeping both incoming BT pairing requests and the BT devices located around. Every update of a BT device nearby triggers an update of the ObservableCollection instance. Updates of the ObservableCollection object remove all incoming BT pairing requests.  When there are a few BT devices around, the ObservableCollection content changes too frequently. So it's getting very complicated/impossible to accept any incoming BT requests.

**Comment by sergeyDoroshenko** [comment]
@namkedia

**Comment by saraclay** [comment]
Hi @sergeyDoroshenko, have you tried the latest IoT builds? The code was updated roughly two weeks ago. This should have helped this issue.

**Comment by saraclay** [comment]
As an FYI - the UI will look different with separate inbound and outbound pairing information status lines.

**Comment by sergeyDoroshenko** [comment]
Thanks @saraclay. Do you have ETA for new code on GitHub?

**Comment by saraclay** [comment]
Hi @sergeyDoroshenko, the Insider Build 17083 is available. See release notes here: https://docs.microsoft.com/en-us/windows/iot-core/release-notes/insider/17083
