### ISSUE TITLE
Why does the link of opencv documentation is redirected and cannot be seen now

### ISSUE THREAD

**Issue by Ichangeling** [Microsoft/Windows-iotcore-samples#92]
The documentation of opencv sample is redirected and cannot be seen from last week.
Is there any way to see that now?
@namkedia

**Comment by saraclay** [comment]
Hello - can you please repro what you're seeing?

**Comment by Ichangeling** [comment]
![image](https://user-images.githubusercontent.com/7472025/36218727-4eb16ea0-11f0-11e8-8513-5549b162baa5.png)

**Comment by Ichangeling** [comment]
https://github.com/Microsoft/Windows-iotcore-samples/blob/develop/Samples/OpenCVExample/CPP/README.md

If I clicked the link of the documentation on this page, then instead of the doc, it shows

> Redirecting you to WindowsOnDevices.com... Click here if you are not automatically redirected.

And then I just redirected back to the previous page again.

**Comment by saraclay** [comment]
Ah, thanks for pointing this out. I will get this fixed.

**Comment by saraclay** [comment]
Hello - this problem has been resolved. Thank you for pointing this out!
